//Se importan las librerías a utilizar en la aplicación;
import java.io.File; //Para leer archivos.
import javax.sound.sampled.AudioSystem; //Manipular archivos de tipo 'audio'.
import javax.sound.sampled.Clip; //Utilizar comandos 'clip'.

/**
 *
 * @author Gustavo Rivero
 * GitHub: gustavoerivero
 */

/*
 * IMPORTANTE ACLARAR:
 * °Para la elaboración de esta aplicación se utilizó NetBeans IDE 8.2
 *
 * °Para el aspecto visual de la aplicación:
 *      - En la parte del código que vean '* Set the Nimbus look and feel *', justo
 *      en la línea donde se muestra 'if ("Nimbus".equals(info.getName())) {' van a
 *      cambiar el 'Nimbus' por 'Windows'.
 *      - En las propiedades del jFrame deben seleccionar la opción 'undercorated' y
 *      retirar la opción 'rezisable'.
 *      - Para un manejo más fácil en el apartado visual, aplicar un 'AbsoluteLayout'.
 *      - En mi caso, para el uso de botones utilicé 'jPanel'.
 */
public class Solicitud extends javax.swing.JFrame {

    /* 
     * Se declaran e inicializan las variables a utilizar;
     * xx: Representará la ubicación del Mouse con respecto al eje horizontal o
     *     eje X.
     * xy: Representará la ubicación del Mouse con respecto al eje vertical o
     *     eje Y.
     * ily: Se instancia la clase LuvYa. Para el uso de la ventana emergente que
     *     dará por culminado el uso de la aplicación
     */
    int xx = 0, xy = 0;
    LuvYa ily = new LuvYa();
    
    
    /**
     * Creates new form Solicitud
     */
    public Solicitud() {
        initComponents();
        
        //Se posiciona la ventana en el centro de la pantalla.
        setLocationRelativeTo(null);
        
        /*
         * Se define la dirección de la canción de fondo que se va a utilizar.
         * Es bueno resaltar que el formato del audio a utilizar se encuentra
         * en 'wav'.
         *
         * PD: Utilicé un clásico de Elvis Presley (Can't Help Falling In Love)
         * para esta aplicación, puede sustituirse por la que gusten.
         */
        String directorio = new File ("Sonido/Elvis Presley - Cant Help Falling In Love (Audio).wav").getAbsolutePath();

        try {
            
            //Se obtiene un Clip de sonido
            Clip sonido = AudioSystem.getClip();
            
            //Se carga con un fichero wav
            sonido.open(AudioSystem.getAudioInputStream(new File(directorio)));
            
            //Comienza la reproducción
            sonido.start();
            
            //Reproduce el fichero de sonido una y otra vez sin parar.
            sonido.loop(Clip.LOOP_CONTINUOUSLY); 
            
        } catch (Exception e) {
            System.out.println("" + e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));

        jPanel2.setBackground(new java.awt.Color(255, 153, 255));

        jLabel1.setBackground(new java.awt.Color(204, 0, 153));
        jLabel1.setFont(new java.awt.Font("Elephant", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿Quieres ser mi novia?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 102, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel3MouseMoved(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Elephant", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Si");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 102, 255));
        jPanel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel7MouseMoved(evt);
            }
        });
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Elephant", 2, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("No");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 396, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Método que agrega un bordeado en el jPanel al posicionar el mouse encima del mismo.
    private void jPanel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseMoved
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204,0,153)));
    }//GEN-LAST:event_jPanel3MouseMoved

    //Método que retira el bordeado del jPanel al quitar el mouse encima del mismo.
    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,153,255)));
    }//GEN-LAST:event_jPanel3MouseExited

    //Método que hace visible el 'mensaje emergente' y oculta este jFrame.
    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        ily.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    /*
     * Método que al posicionar el mouse encima del jPanel ubica a este último
     * en una ubicación aleatoria dentro del jFrame.
     */
    private void jPanel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseMoved
       /*
        * Método que agrega bordeado del jPanel al posicionar el mouse encima
        * del mismo, sin embargo, es algo que no va a ocurrir.
        */
       jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204,0,153)));
       
       //Obtiene la posición del mouse con respecto al eje X y eje Y.
       xx = evt.getX(); //Posición en el eje X.
       xy = evt.getY(); //Posición en el eje Y.
       
       /* 
        * Se declaran e inicializan variables que toman el tamaño total que
        * tiene el jFrame. Se obtienen estos valores en variables separadas;
        * 'x' para el ancho del jFrame y 'y' para el alto del jFrame.
        */
       int x = this.getWidth(), y = this.getHeight();
       
       /*
        * Se declara un nuevo valor para las variables 'x' y 'y';
        * se utiliza el método Math.random() para obtener un valor numérico
        * aleatorio el cual será multiplicado por el ancho/largo del jFrame y
        * posteriormente, se le resta el valor de la posición actual del Mouse.
        */
       x = (int) (Math.random()*x-xx);
       y = (int) (Math.random()*y-xy);
       
       /*
        * Por último, se ubica al jPanel en la nueva ubicación obtenida por 
        * las variables 'x' y 'y'
        */
       jPanel7.setLocation(x,y);
    }//GEN-LAST:event_jPanel7MouseMoved
    
    //Método que retira el bordeado del jPanel al quitar el mouse encima del mismo.
    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,153,255)));
    }//GEN-LAST:event_jPanel7MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Solicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Solicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Solicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Solicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Solicitud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
